# Generated by Django 4.0.2 on 2022-02-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=200)),
                ('airline_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.airline'),
            preserve_default=False,
        ),
    ]
